mongoserver:
  image: mongo:3.7.9

portalen_web:
  image: telemark/portalen-web:latest@sha256:12609349cd89996227659e1b02bf6daebe81b5f2aec48df1b3e31bf0141179b0
  container_name: portalen_web
  env_file: portalen.env
  restart: always
  links:
    - mongoserver
  ports:
    - 8080:8080
    - 3030:3030
