mongoserver:
  image: mongo:3.7.9

portalen_web:
  image: telemark/portalen-web:latest@sha256:c769faca77e1438ceae1f86edade46c4c3b599fe567578fbf0fcdeea43b02455
  container_name: portalen_web
  env_file: portalen.env
  restart: always
  links:
    - mongoserver
  ports:
    - 8080:8080
    - 3030:3030
