mongoserver:
  image: mongo:3.7.9

portalen_web:
  image: telemark/portalen-web:latest@sha256:4c6cef86676d8d3dfe90576ad8fed937741c22ac6a35f6af5a30954d8229972c
  container_name: portalen_web
  env_file: portalen.env
  restart: always
  links:
    - mongoserver
  ports:
    - 8080:8080
    - 3030:3030
