mongoserver:
  image: mongo:3.7.9

portalen_web:
  image: telemark/portalen-web:latest@sha256:5d26f9cbb61f78c85f661c9b12dd12554ae3d77540c4d22e651e5691c6ddeb5a
  container_name: portalen_web
  env_file: portalen.env
  restart: always
  links:
    - mongoserver
  ports:
    - 8080:8080
    - 3030:3030
