mongoserver:
  image: mongo:3.4.1

portalen_web:
  image: telemark/portalen-web:latest@sha256:db78cb5a8cb8d883eb1ea0b54fc5f97e7512235c377189a67f4c48dec7bb630d
  container_name: portalen_web
  env_file: portalen.env
  restart: always
  links:
    - mongoserver
  ports:
    - 8080:8080
    - 3030:3030
