mongoserver:
  image: mongo:3.7.9

portalen_web:
  image: telemark/portalen-web:latest@sha256:78f0b4ef4b1b28eff866a51579f09bb806af8076ccbca1d605445e14ed8578d5
  container_name: portalen_web
  env_file: portalen.env
  restart: always
  links:
    - mongoserver
  ports:
    - 8080:8080
    - 3030:3030
